"""0005_check_runs

Revision ID: 1aa4ab55e807
Revises: 884686d14423
Create Date: 2026-07-30 01:46:37.629466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa4ab55e807'
down_revision: Union[str, Sequence[str], None] = '884686d14423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surface_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='checkrunstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['surface_id'], ['surfaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_runs_id'), 'check_runs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_check_runs_id'), table_name='check_runs')
    op.drop_table('check_runs')
    sa.Enum(name='checkrunstatus').drop(op.get_bind(), checkfirst=True)
