"""0006_visual_diff

Revision ID: 2c2732e66864
Revises: 1aa4ab55e807
Create Date: 2026-07-30 01:54:20.825337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2732e66864'
down_revision: Union[str, Sequence[str], None] = '1aa4ab55e807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_logs', sa.Column('visual_diff_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_logs', 'visual_diff_score')
    # ### end Alembic commands ###
