"""0010_battlecards_response_library

Revision ID: 389463398202
Revises: ae626c341656
Create Date: 2026-07-30 11:25:49.669860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '389463398202'
down_revision: Union[str, Sequence[str], None] = 'ae626c341656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battlecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id')
    )
    op.create_index(op.f('ix_battlecards_id'), 'battlecards', ['id'], unique=False)
    op.create_table('response_library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_library_items_id'), 'response_library_items', ['id'], unique=False)
    op.create_table('battlecard_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('battlecard_id', sa.Integer(), nullable=False),
    sa.Column('proposed_content_markdown', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('source_change_log_ids', sa.JSON(), nullable=True),
    sa.Column(
        'status',
        postgresql.ENUM('pending', 'approved', 'rejected', name='approvalstatus', create_type=False),
        nullable=False
    ),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['battlecard_id'], ['battlecards.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battlecard_updates_id'), 'battlecard_updates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_battlecard_updates_id'), table_name='battlecard_updates')
    op.drop_table('battlecard_updates')
    op.drop_index(op.f('ix_response_library_items_id'), table_name='response_library_items')
    op.drop_table('response_library_items')
    op.drop_index(op.f('ix_battlecards_id'), table_name='battlecards')
    op.drop_table('battlecards')
    # ### end Alembic commands ###
