"""0012_company_profiles

Revision ID: 6d761b03016c
Revises: f83c91a44081
Create Date: 2026-07-30 11:51:20.850229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d761b03016c'
down_revision: Union[str, Sequence[str], None] = 'f83c91a44081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('hq_location', sa.String(), nullable=True),
    sa.Column('employee_range', sa.String(), nullable=True),
    sa.Column('funding_stage', sa.String(), nullable=True),
    sa.Column('key_people', sa.JSON(), nullable=True),
    sa.Column('notes_markdown', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id')
    )
    op.create_index(op.f('ix_company_profiles_id'), 'company_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_profiles_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
