"""0004_llm_scoring

Revision ID: 884686d14423
Revises: 3ab96e40ea8c
Create Date: 2026-07-30 01:41:03.864887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884686d14423'
down_revision: Union[str, Sequence[str], None] = '3ab96e40ea8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('scoring', 'classification', 'briefing', 'embedding', name='llmusagepurpose'), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_logs_id'), 'token_usage_logs', ['id'], unique=False)
    op.add_column('change_logs', sa.Column('rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('change_logs', 'rationale')
    op.drop_index(op.f('ix_token_usage_logs_id'), table_name='token_usage_logs')
    op.drop_table('token_usage_logs')
    sa.Enum(name='llmusagepurpose').drop(op.get_bind(), checkfirst=True)
