"""0001_baseline

Revision ID: 8c785b33b579
Revises: 
Create Date: 2026-07-30 01:12:17.691256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c785b33b579'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    This was originally generated via `--autogenerate` against a dev DB that
    already had these tables from the pre-Alembic `Base.metadata.create_all`
    era, so the autogenerated diff was empty (a documented "no-op" at the
    time). That meant a genuinely fresh database — one that never went
    through `create_all` — had no migration that ever created `users`,
    `competitors`, or `change_logs`, and `alembic upgrade head` failed at
    migration 0002 (which reads/alters those tables) with `relation "users"
    does not exist`. Filled in here with the actual pre-0002/0003 shape of
    each table, reconstructed from what later migrations alter/drop.
    """
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('competitors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('last_snapshot', sa.Text(), nullable=True),
        sa.Column('check_frequency', sa.String(), nullable=True),
        sa.Column('last_checked_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)

    op.create_table('change_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('competitor_id', sa.Integer(), nullable=False),
        sa.Column('old_snapshot', sa.Text(), nullable=True),
        sa.Column('new_snapshot', sa.Text(), nullable=True),
        sa.Column('diff', sa.Text(), nullable=True),
        sa.Column('materiality_score', sa.Integer(), nullable=True),
        sa.Column('classification', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_logs_id'), 'change_logs', ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_change_logs_id'), table_name='change_logs')
    op.drop_table('change_logs')
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
