"""0008_audit_fixes

Revision ID: 9b453eb18bfb
Revises: ec0e9aeacad5
Create Date: 2026-07-30 11:01:43.558650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b453eb18bfb'
down_revision: Union[str, Sequence[str], None] = 'ec0e9aeacad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_budgets',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('monthly_cap_usd', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('alert_threshold_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_budgets')
    # ### end Alembic commands ###
