"""0007_change_embeddings

Revision ID: ec0e9aeacad5
Revises: 2c2732e66864
Create Date: 2026-07-30 02:00:54.871837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0e9aeacad5'
down_revision: Union[str, Sequence[str], None] = '2c2732e66864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_log_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_log_id')
    )
    op.create_index(op.f('ix_change_embeddings_id'), 'change_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_embeddings_id'), table_name='change_embeddings')
    op.drop_table('change_embeddings')
    # ### end Alembic commands ###
