"""0011_workspace_integrations

Revision ID: f83c91a44081
Revises: 389463398202
Create Date: 2026-07-30 11:38:48.842751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83c91a44081'
down_revision: Union[str, Sequence[str], None] = '389463398202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('slack', 'email', 'crm', name='integrationprovider'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider', name='uq_workspace_integration_provider')
    )
    op.create_index(op.f('ix_workspace_integrations_id'), 'workspace_integrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_workspace_integrations_id'), table_name='workspace_integrations')
    op.drop_table('workspace_integrations')
    sa.Enum(name='integrationprovider').drop(op.get_bind(), checkfirst=True)
